#!/bin/awk -f
# reads flag in SAM file and adds "/1" or "/2" to the read id depending on the flag
function num_in_pair(flag) {
    is_first_in_pair = and(flag, 0x40);
    is_second_in_pair = and(flag, 0x80);
    if (!xor(is_first_in_pair, is_second_in_pair))
	num = "?";
    else if ( is_first_in_pair )
	num = "1";
    else if ( is_second_in_pair )
	num = "2";
    return num;
}

BEGIN { FS="\t"; OFS="\t";}
!/^@/ {
    id=$1
    flag=$2
    #print rest of line
    remove_ncols=1 
    tail=$0;
    for (i=1;i<=remove_ncols;i++) sub($i,"",tail); sub(/^[ \t]+/,"",tail)
    print $1"/"num_in_pair(flag),tail
}