#!/bin/bash
# does the ls of the arguments on karthur
# lists the matching files in scp_files
# makes run{0..9}.sh executables
# executes them all with screen

# you must make sure that the "screen -c ~/zsh-functions/screenrc_scp" line is pointing to the right file
# also a good idea to add alias scp10='noglob scp10' to your .zshrc

touch run{0..9}.sh
n=0
for i in "$@" 
do cat << EOF >> run$(( $n % 10 )).sh
curl -C - -o $i -k --user "etiacci@solido.umbria.it:br65zmxv" https://data.fasteris.com/private/GGP/GGP-50-61/analysis/$i
sleep 10
EOF
    n=$(( $n + 1 ))
done
chmod +x run*.sh
screen -c /ifs/scratch/c2b2/rr_lab/avp2106/scripts/screenrc_scp
#rm -rf run*.sh 
